# Generated by Django 4.1 on 2024-11-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255, unique=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField(auto_now_add=True, null=True)),
                ("done", models.BooleanField(default=False)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="tags", to="task_tag.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_time"],
            },
        ),
    ]
